@startuml GUI state machine
[*] --> idle : E_Startup / Init(), Get_MQTT_Data() 

state valid <<choice>>
idle : displays current charging status 
idle --> valid : E_RFID_Scanned / Validate_RFID()
idle --> idle : E_Plug_Removed / Update_Start_Screen()


valid --> invalid_user : [Invalid_RFID]
valid --> valid_user : [Valid_RFID]

invalid_user : gives warning INVALID 
invalid_user --> idle : E_Timer_Elapsed / Get_MQTT_Data()

valid_user : displays information of the user
valid_user --> idle : E_Timer_Elapsed / Get_MQTT_Data(), Update_Start_Screen()


@enduml
